# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1baf1026d848e9e58145c7e89875dae36c2c2a4cad3643ac2cf3af81cff73932d30e8807992bf3b87226b4f0492e5e9dd48d1622bac75faf60cc8ae6019187c4

test:
  secret_key_base: 675141173e2b880e25028ea1a9b1c869ffd3ac8fde07c270e24c5ac0942cb222c681553d9d57e84ef906296ba9af9acbd4de2046c6ff88b634066d74974fae56

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
